name: Build Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - images/**

jobs:
  build:
    name: "images:${{ matrix.image }}"
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ["rclone-sync"]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./images/${{ matrix.image }}
          tags: ghcr.io/brooke-ec/images:${{ matrix.image }}
          push: true
